[MIG] Migration product_internal_code to V11
ingadhoc/product pull request #126
Opened 2018-04-25 11:18 UTC by ValentinoDefelice

2018-04-25 11:45 UTC, nicomacr reviewed
@ValentinoDefelice you forgot to change the view file path in manifest.py to "views"

2018-04-27 16:45 UTC, nicomacr commented
@ValentinoDefelice separe to 2 archive the models product.product and product.template
https://github.com/adhoc-dev/product/blob/9b6d95bfa721a5669eb3ac9dd85a2dd527a53cc8/product_internal_code/models/product.py#L43

2018-05-02 16:27 UTC, jjscarafia requested changes
Cambiaría el readme por algo así:

This module creates a new field called "Internal Code" on products.
Internal Code must be unique per product.
It also creates a sequence to populate this new field automatically upon product creation.

Configuration:
You can change or delete the default sequence called "product.internal.code" sequences menu.

Usage:
Create a product and you can:
* set an internal code
* or leave it empty, then a new code will be automatically assigned by the "product.internal.code" sequence

2018-05-15 21:18 UTC, jjscarafia approved these changes

2018-05-15 21:18 UTC, merged